#!/bin/bash

export COLLIBRA_COMMUNITY_NAME=""
export COLLIBRA_COMMUNITY_DESCRIPTION=""
export COLLIBRA_URL=""
export COLLIBRA_USERNAME=""
export COLLIBRA_PASSWORD=""
export HTTP_ODBC_URL=""
export HTTP_ODBC_RULE_QUERY="SELECT * FROM \"RULES\""
export HTTP_ODBC_PROFILE_QUERY="SELECT * FROM \"PROFILES\""
export COLLIBRA_DEBUG_LEVEL="debug"
export COLLIBRA_MULTI_COMMUNITY=true

node lib/collibra/collibra-connector.js



