interface PandoraRule {
  "NAME": string;
  "SCORE": string;
  "MEASURE": string;
  "PASSED MEASURE": string;
  "FAILED MEASURE": string;
  "RULE CATEGORY": string;
  "DESCRIPTION": string;
  "INCLUDED": string;
  "FILTER": string;
  "ROWS PASSED": string;
  "ROWS FAILED": string;
  "TABLE": string;
  "TABLE VERSION": string;
  "VERSIONS OFFSET": string;
  "COLUMN": string;
  "SCHEMA": string;
  "FUNCTION": string;
  "VERSION": string;
  "PARAMETERS": string;
  "TYPE": string;
  "ROWS CONSIDERED": string;
  "ROWS IGNORED": string;
  "PASSED": string;
  "FAILED": string;
  "CONSIDERED": string;
  "IGNORED": string;
  "CATEGORY": string;
  "TABLE CREATED": string;
  "LAST VALIDATED": string;
  "CONNECTION STRING": string;
  "EXTERNAL COLUMN NAME": string;
  "EXTERNAL DATABASE": string;
  "EXTERNAL SCHEMA": string;
  "EXTERNAL SERVER": string;
  "EXTERNAL TABLE NAME": string;
  "FAIL RANGE": string;
  "FAILED SCORE": string;
  "LATEST TABLE VERSION": string;
  "PASS RANGE": string;
  "RESULT": string;
  "RULE CATEGORY ID": string;
  "RULE THRESHOLD": string;
}
